// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250326232822_order_2")]
    partial class order_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_washer_accepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("payment_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("review_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("selectedWasherId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("serviceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("service_amount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("service_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("workStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
